### ISSUE TITLE
HDF5 file possibly corrupted

### ISSUE THREAD

**Issue by Flyverdragt** [mollerhoj/Scandinavian-ULMFiT#1]
After downloading the .h5 file (129 MB) from Git LFS I haven't been able to open the file using h5py:

`import h5py
r = h5py.File("dawt_enc.h5", "r")

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/theisras/.local/lib/python3.5/site-packages/h5py/_hl/files.py", line 312, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "/home/theisras/.local/lib/python3.5/site-packages/h5py/_hl/files.py", line 142, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 78, in h5py.h5f.open
OSError: Unable to open file (file signature not found)
`

To debug the error I tried running h5debug tool but still received the following error:

`h5debug "dawt_enc.h5"

HDF5-DIAG: Error detected in HDF5 (1.8.16) thread 140603273537280:
  #000: ../../../src/H5F.c line 604 in H5Fopen(): unable to open file
    major: File accessibilty
    minor: Unable to open file
  #001: ../../../src/H5Fint.c line 1087 in H5F_open(): unable to read superblock
    major: File accessibilty
    minor: Read failed
  #002: ../../../src/H5Fsuper.c line 277 in H5F_super_read(): file signature not found
    major: File accessibilty
    minor: Not an HDF5 file
cannot open file`

**Comment by Flyverdragt** [comment]
**Update**

The HDF5 file can be read using pytorch:
'torch.load("dawt_enc.h5")'
